accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views
from .forms import LoginForm

app_name = 'accounts'
urlpatterns = [
    path('register/',views.register,name='register'),
    path('login/', auth_views.LoginView.as_view(template_name='account/login.html',redirect_authenticated_user=True, authentication_form=LoginForm), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='account/logout',next_page ="/"), name='logout'),
    path('sign_up',views.sign_up,name='deconnection')
]

myblog/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('posts.urls')),
    path('accounts/',include('accounts.urls')),
]
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

posts/urls.py
from django.urls import path
from .import views
app_name='posts'

urlpatterns = [
    path('',views.index, name='index'),
    path('post/<int:id>/',views.show,name='show'),
    path('new post/',views.new_post, name='new_post'),
    path('update_post/<int:id>/',views.update_post, name='update_post'),
    path('delete_post/<int:id>/',views.delete_post, name='delete_post'),
    path('search_posts/',views.search_posts, name='search_posts'),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class profile(models.Model):
    user=models.OneToOneField(User,on_delete=models.CASCADE,related_name="profile")
    birthday=models.DateField()
    phonenumber=models.IntegerField()
    
    def __str__(self):
        return self.user.username

comptes/models.py
from django.db import models

# Create your models here.

posts/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Post(models.Model):
    title = models.CharField(max_length=55)
    content =models.TextField()
    image =models.ImageField(upload_to='post_image/')
    user =models.ForeignKey(User,on_delete=models.CASCADE)
    
    def _str_init(self):
        return self.title

accounts/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm,UserCreationForm
from django.contrib.auth.models import User
from .models import profile

class LoginForm(AuthenticationForm):
    username =forms.CharField(label='username',widget=forms.TextInput(attrs={'class':'form-control',}))
    password =forms.CharField(label='password',widget=forms.PasswordInput(attrs={'class':'form-control',}))
    
class Userform(UserCreationForm):
    username =forms.CharField(label='username',widget=forms.TextInput(attrs={'class':'form-control',}))
    email =forms.CharField(label='Email',widget=forms.EmailInput(attrs={'class':'form-control',}))
    password1 =forms.CharField(label='password1',widget=forms.PasswordInput(attrs={'class':'form-control',}))
    password2 =forms.CharField(label='Confirm your password',widget=forms.PasswordInput(attrs={'class':'form-control',}))
    class Meta:
        model =User
        fields=('username','email','password1','password2')
        
class ProfileForm(forms.ModelForm):
    birthday =forms.DateField(label='birthday',widget=forms.DateInput(attrs={'class':'form-control','type':'date',}))
    phonenumber =forms.IntegerField(label='phonenumber',widget=forms.TextInput(attrs={'class':'form-control','type':'number',}))
    class Meta:
        model = profile
        fields = ("birthday","phonenumber")

	

posts/forms.py
from django import forms
from django.forms  import FileInput
from. models import Post

class PostForm(forms.ModelForm):
	title =forms.CharField(label='title',widget=forms.TextInput(attrs={'class':'form-control',}))
	content =forms.CharField(label='content',widget=forms.Textarea(attrs={'class':'form-control',}))
	image = forms.ImageField(label='Image', widget=FileInput(attrs={'class': 'form-control-file'}))
	class Meta:
		model=Post
		fields=('title','content','image')

accounts/views.py
from django.shortcuts import render,redirect
# from django.contrib.auth.forms import UserCreationForm
from .forms import Userform,ProfileForm

# Create your views here.
def register(request):
    if request.user.is_authenticated:
        return redirect('post:index')
        
    if request.method == "POST":
        form =Userform(request.POST)
        profile_form =ProfileForm(request.POST)
        
        if form.is_valid() and profile_form.is_valid():
            user=form.save(commit=False)
            
            profile = profile_form.save(commit=False)
            profile.user =user
            
            user.save()
            profile.save()
            return redirect('accounts:login')
            
    else:
        form =Userform()
        profile_form =ProfileForm()
        
    
        
    context={
        'form':form,
        'profile':profile_form,
    }
    return render(request,'account/register.html',context)

def sign_up(request):
    return render(request,'account/logout.html')

comptes/views.py
from django.shortcuts import render

# Create your views here.

posts/views.py
from django.shortcuts import render ,redirect
from posts.models import Post
from .forms import PostForm
from django.contrib.auth.decorators import login_required
from django.http import Http404
from django.db.models import Q
from django.core.paginator import Paginator

# Create your views here.

@login_required
def index(request):
    posts=Post.objects.order_by('-id').all()
    paginator=Paginator(posts,6)
    page_number=request.GET.get('page')
    page_object=paginator.get_page(page_number)
    post_number=posts.count()
    message=f'{post_number} posts:'
    if post_number==1:
        message=f'{post_number}post:'
        
    context={
        'posts':page_object,
        'post_number':post_number,
        'message':message,
    }
    
    return render(request,'posts/index.html',context)

@login_required
def show(request,id):
    post=Post.objects.get(id=id)
    context ={
        'post':post,
    }
    return render(request,'posts/show.html', context )

@login_required
def new_post(request):
    if request.method == 'POST':
        form=PostForm(request.POST,request.FILES)
        if form.is_valid():
            form=form.save(commit=False)
            form.user=request.user
            form.save()
            return redirect('posts:index')
    else:
        form=PostForm()
        context={
		 'form':form,
		}
    return render(request,'posts/new_post.html',context)
 
@login_required
def update_post(request, id):
    post=Post.objects.get(id=id)
    
    if post.user == request.user:
        if request.method == 'POST':	
            form=PostForm(request.POST,request.FILES,instance=post)
            if form.is_valid():
                form.save()
            return redirect('posts:index')
        else:
            form=PostForm(instance=post)
    else:
        raise Http404
    context={
        'form':form,
        'post':post,
        }
    return render(request,'posts/update_post.html', context)
    

@login_required
def delete_post(request,id):
    post=Post.objects.get(id=id)
    if post.user == request.user:
        
        post.delete()
    else:
        raise Http404
    return redirect('posts:index')
    return render(request,'posts/delete.html')

@login_required
def search_posts(request):
    
    search=request.GET.get('search')
    posts=Post.objects.filter(Q(title__icontains=search) |
                              Q(content__icontains=search) |
                              Q(image__icontains=search))
    
    # posts=Post.objects.order_by('-id').all()
    post_number=posts.count()
    message=f'{post_number} results:'
    if post_number==1:
        message=f'{post_number}result:'
    context={
        'posts':posts,
        'message':message,
    }
    return render(request,'posts/search_posts.html',context)

accounts/templates/layouts/base.html
{% extends "layouts/base.html" %}
{%load static %}

{% block title %}logout{% endblock title %}
{% block stylesheets %}
<link rel="stylesheet" type="text/css" href="{% static "accounts/css/style.css" %}">
{% endblock stylesheets %}

posts/templates/posts/index.html
{% extends "layouts/base.html" %}
{%load static %}

{% block title %}all posts{% endblock title %}
{% block stylesheets %}
<link rel="stylesheet" type="text/css" href="{% static "css/style.css" %}">
{% endblock stylesheets %}

{% block body %}
<h1>{{message}}</h1>
<div class="row row-cols-md-3 row-cols-sm-2">
{% for post in posts %}
<div class="col">
<div class="card shadow" style="width: 18rem;">
{% if post.image %}
  <img src="{{ post.image.url }}" class="card-img-top" alt="...">
  {% endif %}
 <div class="card mb-3 shadow">
	<div class="card-body">
		<h5 class="card-title">{{post.title}}</h5>
		<p class="card-title">{{post.content|truncatechars:'30'}}</p>
		<a href="{% url 'posts:show' post.id %}" class='btn btn-primary'>more</a>
		{% if post.user == request.user %}
		<a href="{% url 'posts:update_post' post.id %}" class='btn btn-success'>update_post</a>
		<a href="{% url 'posts:delete_post' post.id %}" class='btn btn-danger'>delete_post</a>
		{% endif %}
		
	</div>
	<div class="card-footer">
		{{post.user.username}}
	</div>
 </div>
</div>
</div>


{% endfor %}
<nav>
	<ul class="pagination justify-content-center"></ul>
	{% if posts.has_previous %}
	<li class='page-item'>
		<a class='page-link' href='?page={{posts.previous_page_number}}'>
			<span aria-hidden='true'>&laquo;</span>
		</a>
	</li>
	{% endif %}
	<li class='page-item'>
		<p class="page_link text-muted">page{{post.number}} of {{ posts.paginator.num_pages }} </p>
	</li>
	{% if posts.has_next %}
	<li class='page-item'>
		<a class='page-link' href='?page={{posts.next_page_number}}'>
			<span aria-hidden='true'>&raquo;</span>
		</a>
	</li>
	{% endif %}
</nav>
{% endblock body %}

posts/templates/posts/new_post.html
{% extends 'layouts/base.html' %}

{% load static %}
{% block title %}new_posts{% endblock title %}

{% block stylesheets %}
<link rel="stylesheet" type="text/css" href="{% static "css/style.css" %}">
{% endblock stylesheets %}
{% block body %}


<div class='container'>
 <div class='row'>
  <div class='col-md-8 mx-auto'>
  <h1 class='text-center mb-4'>New post </h1>
   <form action='' method='POST'enctype='multipart/form-data' >
   {% if form.subject.errors %}
   {% for error in form.subject.errors %}
   <p class='text-danger' > <strong>{{ error }}</strong></p>
   {% endfor%}
   {% endif %}
   {% csrf_token %}
   {% for field in form %}
   <div class='form-group'>
    <strong>{{ field.label_tag }}</strong>
    <img src="{{ post.image.url }}" alt="{{ post.title }}">
    {{field}}
    {% if field.help_text %}
    <p class='help'>{{ field.help_text }}</p>
    {% if field.error %}
   {% for error in field.error %}
   <p class='text-danger' > <strong>{{ error }}</strong></p>
   {% endfor%}
   {% endif %}
    {% endif %}
   </div>
   {% endfor %}
   <input type='submit' class='btn btn-primary' value='post'>
  </div>
 </div>
 <div class='col-md-4'></div>
</div>
{% endblock body %}

posts/templates/posts/search_posts.html
{% extends "layouts/base.html" %}
{% load static %}
{% block title %}search results{% endblock title %}

{% block stylesheets %}
<link rel="stylesheet" type="text/css" href="{% static "css/style.css" %}">
{% endblock stylesheets %}
{% block body %}
<h3>{{message}}</h3>

<div class="row row-cols-md-3 row-cols-sm-2">
{% for post in posts %}
<div class="col">
<div class="card shadow" style="width: 18rem;">
{% if post.image %}
  <img src="{{ post.image.url }}" class="card-img-top" alt="...">
  {% endif %}
 <div class="card mb-3 shadow">
	<div class="card-body">
		<h5 class="card-title">{{post.title}}</h5>
		<p class="card-title">{{post.content|truncatechars:'30'}}</p>
		<a href="{% url 'posts:show' post.id %}" class='btn btn-primary'>more</a>
		{% if post.user == request.user %}
		<a href="{% url 'posts:update_post' post.id %}" class='btn btn-success'>update_post</a>
		<a href="{% url 'posts:delete_post' post.id %}" class='btn btn-danger'>delete_post</a>
		{% endif %}
		
	</div>
	<div class="card-footer">
		{{post.user.username}}
	</div>
 </div>
</div>
</div>


{% endfor %}
{% endblock body %}

posts/templates/posts/show.html
{% extends "layouts/base.html" %}
{% load static %}
{% block title %}Detail{% endblock title %}

{% block stylesheets %}
<link rel="stylesheet" type="text/css" href="{% static "css/style.css" %}">
{% endblock stylesheets %}

{% block body %}
<div class="card shadow" >
    {% if post.image %}
      <img src="{{ post.image.url }}" class="card-img-top" alt="...">
      {% endif %}
     <div class="card mb-3 shadow">
        <div class="card-body">
            <h5 class="card-title">{{post.title}}</h5>
            <p class="card-title">{{post.content}}</p>
        </div>
    </div>
    {% if post.user == request.user %}
    <div class="card-footer">
        <a href="{% url 'posts:update_post' post.id %}" class='btn btn-success'>update_post</a>
		<a href="{% url 'posts:delete_post' post.id %}" class='btn btn-danger'>delete_post</a>
    </div>
    {% endif %}
{% endblock body %}

posts/templates/posts/update_post.html
{% extends "layouts/base.html" %}
{% load static %}
{% block title %}Detail{% endblock title %}

{% block stylesheets %}
<link rel="stylesheet" type="text/css" href="{% static "css/style.css" %}">
{% endblock stylesheets %}

{% block body %}


<div class='container'>
 <div class='row'>
  <div class='col-md-8 mx-auto'>
  <h1 class='text-center mb-4'>update post {{post.title}} </h1>
   <form action='' method='POST'enctype='multipart/form-data' >
   {% if form.subject.errors %}
   {% for error in form.subject.errors %}
   <p class='text-danger' > <strong>{{ error }}</strong></p>
   {% endfor%}
   {% endif %}
   {% csrf_token %}
   {% for field in form %}
   <div class='form-group'>
    <strong>{{ field.label_tag }}</strong>
    
    {{field}}
    {% if field.help_text %}
        <p class='help'>{{ field.help_text }}</p>
    {% endif %}
    {% if field.error %}
        {% for error in field.error %}
            <p class='text-danger' > <strong>{{ error }}</strong></p>
        {% endfor%}
    {% endif %}
    
    
   </div>
   {% endfor %}
   <img src="{{ post.image.url }}" width='200'>
   <input type='submit' class='btn btn-primary' value='update post'>
  </div>
 </div>
 <div class='col-md-4'></div>
</div>

{% endblock body %}

templates/layouts/base.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>{% block title %}{% endblock title %}|my blog</title>
        {% block stylesheets %}
        {% endblock stylesheets %}
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    </head>
    <body>
        <header>
            {% include "layouts/partials/header.html" %}
        </header>
        <div class="body container">
            {% block body %}
            <h1>myblog</h1>
            {% endblock body %}
        </div>
        
        <footer class="footer p-3 mt-5 text-center">
            {% include "layouts/partials/footer.html" %}
        </footer>
        <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js" integrity="sha384-0pUGZvbkm6XF6gxjEnlmuGrJXVbNuzT9qBBavbLwCsOGabYfZo0T0to5eqruptLy" crossorigin="anonymous"></script>
    </body>
</html>

templates/layouts/partials/footer.html
<p class="text-center text-light">
	copyright &copy.{% now "D,M,Y" %} &middot Myblog
</p>

templates/layouts/partials/header.html
<nav class="navbar navbar-expand-lg bg-body-tertiary mb-4 shadow">
    <div class='container'>
    <div class="container-fluid">
      <a class="navbar-brand text-white" href="/">Myblog</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      {% if request.user.is_authenticated %}
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active text-white" aria-current="page" href="/">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link text-white" href="{% url "posts:new_post" %}">new post</a>
        </li>
        <li class="nav-item">
          <a class="nav-link text-white" href="{% url "accounts:deconnection" %}">logout</a> </li>
      </ul>
      <div class="d-flex">
        <p class="text-white me-2">Bonjour, {{ request.user.username }}</p>
      </div>
    </div>
{% else %}
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0 ">
        
        <li class="nav-item">
          <a class="nav-link text-white" href="{% url "accounts:login" %}">login</a>
        </li>
        <li class="nav-item">
          <a class="nav-link active text-white" aria-current="page" href="{% url "accounts:register" %}">sign up</a>
        </li>
      </ul>
    </div>
{% endif %}
<form action='{% url "posts:search_posts" %}' method='get' class='d-flex ml-3'>
  <input placeholder='search' class='form-control mr-2' type='search' name='search'></input>
  <button class='btn btn-outline-light ml-2' type='submit'>search</button>
</form>

      
  </nav>